Fixes GenericAssetFile errors: use subList replace of Range
```
Caused by: java.lang.NoSuchMethodError: 'void groovy.lang.IntRange.<init>(boolean, boolean, int, int)'
        at asset.pipeline.GenericAssetFile.getParentPath(GenericAssetFile.groovy:58)
        at asset.pipeline.processors.AbstractUrlRewritingProcessor.replacementUrl(AbstractUrlRewritingProcessor.groovy:92)
```